name: Modify the GCP User Roles (PoC)

on:
  pull_request_target:
    types: [opened, synchronize, reopened, closed]
    paths:
      - 'infra/iam/users.yml'

permissions:
  contents: read
  pull-requests: write

jobs:
  beam_UserRoles:
    runs-on: ubuntu-latest # 替换了 self-hosted 以便你测试
    steps:
      - name: Checkout code (VULNERABLE, Pulls attacker's code)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merged == true && github.base_ref || github.event.pull_request.head.sha }}
          
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2
          
      - name: Initialize Terraform
        working-directory: ./infra/iam
        run: terraform init
        
      - name: Terraform Plan (THE SINK, Executes malicious .tf files)
        working-directory: ./infra/iam
        run: terraform plan -out=tfplan

      - name: Create comment body (Mock)
        if: github.event.action == 'opened'
        run: echo "Plan executed successfully."
